name: CI

on: [push]

jobs:
  TestDotNET:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .Net
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 2.1.607
    - name: First Build
      run: dotnet build ./csharp/Samples.sln --configuration Release




    