name: CI

on: [push]

jobs:
  TestDotNET:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      git submodule init
      git submodule update --recursive
    - name: Setup .Net
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 2.1.607
    - name: First Build
      run: dotnet build ./csharp/Samples.sln --configuration Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: csharp/Functions.Dll/bin




    